Repository ConSol-Lab/Pumpkin, pull requests merged in 2024-10, with the labels that each got.

#53 (Mini PR) Fix out-of-bounds is_restart_pointless for dynamic brancher
  pumpkin-lib/src/branching/branchers/dynamic_brancher.rs
  pumpkin-lib/src/engine/constraint_satisfaction_solver.rs
Labels: bug

#49 Re-introducing checking of Reason
  pumpkin-lib/src/engine/constraint_satisfaction_solver.rs
  pumpkin-lib/src/engine/cp/reason.rs
  pumpkin-lib/src/engine/debug_helper.rs
  pumpkin-lib/src/propagators/arithmetic/integer_multiplication.rs
Labels: bug, enhancement

#56 Adding the logging of statistics for propagators
  Cargo.lock
  pumpkin-cli/Cargo.toml
  pumpkin-cli/src/main.rs
  pumpkin-lib/Cargo.toml
  pumpkin-lib/src/api/mod.rs
  pumpkin-lib/src/api/solver.rs
  pumpkin-lib/src/basic_types/mod.rs
  pumpkin-lib/src/basic_types/moving_averages/cumulative_moving_average.rs
  pumpkin-lib/src/basic_types/statistic_logging.rs
  pumpkin-lib/src/engine/conflict_analysis/conflict_analysis_context.rs
  pumpkin-lib/src/engine/conflict_analysis/recursive_minimisation.rs
  pumpkin-lib/src/engine/conflict_analysis/resolution_conflict_analyser.rs
  pumpkin-lib/src/engine/conflict_analysis/semantic_minimiser.rs
  pumpkin-lib/src/engine/constraint_satisfaction_solver.rs
  pumpkin-lib/src/engine/cp/propagation/propagator.rs
  pumpkin-lib/src/engine/mod.rs
  pumpkin-lib/src/engine/solver_statistics.rs
  pumpkin-lib/src/lib.rs
  pumpkin-lib/src/statistics/mod.rs
  pumpkin-lib/src/statistics/statistic_logger.rs
  pumpkin-lib/src/statistics/statistic_logging.rs
Labels: enhancement

#80 fix: complete proof when propagator initialization identifies root-level conflict
  pumpkin-solver/src/engine/constraint_satisfaction_solver.rs
  pumpkin-solver/src/engine/debug_helper.rs
Labels: bug

#60 feat: incremental backtracking for the cumulative constraint
  pumpkin-solver/src/bin/pumpkin-solver/main.rs
  pumpkin-solver/src/constraints/cumulative.rs
  pumpkin-solver/src/engine/cp/propagation/propagator.rs
  pumpkin-solver/src/engine/cp/propagation/propagator_initialisation_context.rs
  pumpkin-solver/src/propagators/clausal/basic_clausal.rs
  pumpkin-solver/src/propagators/cumulative/options.rs
  pumpkin-solver/src/propagators/cumulative/time_table/explanations/big_step.rs
  pumpkin-solver/src/propagators/cumulative/time_table/explanations/mod.rs
  pumpkin-solver/src/propagators/cumulative/time_table/explanations/naive.rs
  pumpkin-solver/src/propagators/cumulative/time_table/explanations/pointwise.rs
  pumpkin-solver/src/propagators/cumulative/time_table/mod.rs
  pumpkin-solver/src/propagators/cumulative/time_table/over_interval_incremental_propagator/checks.rs
  pumpkin-solver/src/propagators/cumulative/time_table/over_interval_incremental_propagator/debug.rs
  pumpkin-solver/src/propagators/cumulative/time_table/over_interval_incremental_propagator/insertion.rs
  pumpkin-solver/src/propagators/cumulative/time_table/over_interval_incremental_propagator/mod.rs
  pumpkin-solver/src/propagators/cumulative/time_table/over_interval_incremental_propagator/removal.rs
  pumpkin-solver/src/propagators/cumulative/time_table/over_interval_incremental_propagator/time_table_over_interval_incremental.rs
  pumpkin-solver/src/propagators/cumulative/time_table/propagation_handler.rs
  pumpkin-solver/src/propagators/cumulative/time_table/time_table_over_interval_incremental.rs
  pumpkin-solver/src/propagators/cumulative/time_table/time_table_per_point.rs
  pumpkin-solver/src/propagators/cumulative/time_table/time_table_per_point_incremental.rs
  pumpkin-solver/src/propagators/cumulative/time_table/time_table_util.rs
  pumpkin-solver/src/propagators/cumulative/utils/cumulative_structs.rs
  pumpkin-solver/src/propagators/cumulative/utils/mod.rs
  pumpkin-solver/src/propagators/cumulative/utils/sparse_set.rs
  pumpkin-solver/src/propagators/cumulative/utils/structs/mandatory_part_adjustments.rs
  pumpkin-solver/src/propagators/cumulative/utils/structs/mod.rs
  pumpkin-solver/src/propagators/cumulative/utils/structs/parameters.rs
  pumpkin-solver/src/propagators/cumulative/utils/structs/resource_profile.rs
  pumpkin-solver/src/propagators/cumulative/utils/structs/task.rs
  pumpkin-solver/src/propagators/cumulative/utils/structs/updatable_structures.rs
  pumpkin-solver/src/propagators/cumulative/utils/structs/updated_task_info.rs
  pumpkin-solver/src/propagators/cumulative/utils/util.rs
  pumpkin-solver/tests/mzn_constraint_test.rs
Labels: enhancement

#87 feat: implement consistency check interface in linear less than propagator
  pumpkin-solver/src/propagators/arithmetic/linear_less_or_equal.rs
Labels: enhancement

#86 feat: adding option to force incremental cumulative propagators to find the same trace as non-incremental
  Cargo.lock
  Cargo.toml
  pumpkin-macros/Cargo.toml
  pumpkin-macros/src/lib.rs
  pumpkin-solver/Cargo.toml
  pumpkin-solver/src/basic_types/sequence_generators/sequence_generator_type.rs
  pumpkin-solver/src/bin/pumpkin-solver/main.rs
  pumpkin-solver/src/constraints/cumulative.rs
  pumpkin-solver/src/encoders/pseudo_boolean_constraint_encoder.rs
  pumpkin-solver/src/engine/cp/test_helper.rs
  pumpkin-solver/src/engine/sat/learned_clause_manager.rs
  pumpkin-solver/src/propagators/cumulative/options.rs
  pumpkin-solver/src/propagators/cumulative/time_table/explanations/mod.rs
  pumpkin-solver/src/propagators/cumulative/time_table/explanations/pointwise.rs
  pumpkin-solver/src/propagators/cumulative/time_table/mod.rs
  pumpkin-solver/src/propagators/cumulative/time_table/over_interval_incremental_propagator/debug.rs
  pumpkin-solver/src/propagators/cumulative/time_table/over_interval_incremental_propagator/mod.rs
  pumpkin-solver/src/propagators/cumulative/time_table/over_interval_incremental_propagator/synchronisation.rs
  pumpkin-solver/src/propagators/cumulative/time_table/over_interval_incremental_propagator/time_table_over_interval_incremental.rs
  pumpkin-solver/src/propagators/cumulative/time_table/per_point_incremental_propagator/mod.rs
  pumpkin-solver/src/propagators/cumulative/time_table/per_point_incremental_propagator/synchronisation.rs
  pumpkin-solver/src/propagators/cumulative/time_table/per_point_incremental_propagator/time_table_per_point_incremental.rs
  pumpkin-solver/src/propagators/cumulative/time_table/propagation_handler.rs
  pumpkin-solver/src/propagators/cumulative/time_table/time_table_over_interval.rs
  pumpkin-solver/src/propagators/cumulative/time_table/time_table_per_point.rs
  pumpkin-solver/src/propagators/cumulative/time_table/time_table_per_point_incremental.rs
  pumpkin-solver/src/propagators/cumulative/time_table/time_table_util.rs
  pumpkin-solver/src/propagators/cumulative/utils/structs/updatable_structures.rs
  pumpkin-solver/tests/helpers/mod.rs
  pumpkin-solver/tests/mzn_constraint_test.rs
  pumpkin-solver/tests/mzn_constraints/cumulative.template
Labels: enhancement

#96 chore: release pumpkin-solver 0.1.3
  .release-please-manifest.json
  pumpkin-solver/CHANGELOG.md
  pumpkin-solver/Cargo.toml
Labels: autorelease: pending
